version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fast-on-aws-10"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m771dio0ft76"
s3_prefix = "fast-on-aws-10"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AdServerUrl=\"https://l3lk9gfqg9.execute-api.us-east-1.amazonaws.com/default/VASTEndpoint?client=1\" EmailAddress=\"pph@amazon.com\" S3BucketName=\"fast-on-aws-8\" AdOffsetS3TagKeyName=\"AdOffsets\" LogLevel=\"DEBUG\""
image_repositories = []
